name: deploy

on:
  push:
    branches: [ master, develop ]
  # schedule:
  #   - cron: '0 3 * * 0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # - name: Setup PHP with composer
      #   uses: shivammathur/setup-php@master
      #   with:
      #     php-version: '8.1'
      #     tools: composer:2

      # - name: Validate composer.json and composer.lock
      #   run: composer validate

      # - name: Install dependencies
      #   run: composer install --prefer-dist --no-progress --no-suggest

      # - name: Docker login to dockerhub
      #   run: echo ${{ secrets.DOCKER_PASS }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin

      # - name: Docker login to github
      #   run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username $GITHUB_ACTOR --password-stdin

      # - name: Build the Docker image
      #   run: |
      #     docker build \
      #       --file Dockerfile \
      #       --tag docker.pkg.github.com/$GITHUB_REPOSITORY/contact-form:latest \
      #       --tag pulkitjalan/contact-form:latest \
      #       .

      # - name: Push the Docker image to dockerhub
      #   run: docker push pulkitjalan/contact-form:latest

      # - name: Push the Docker image to github
      #   run: docker push docker.pkg.github.com/$GITHUB_REPOSITORY/contact-form:latest
